version: '3'
services:
	spotifyd:
		image: "ggoussard/spotifyd:${ARCH}"
		network_mode: "host"
		devices:
			- "/dev/snd:/dev/snd"
		volumes:
			- "/usr/share/alsa:/usr/share/alsa"
			- "/etc/spotifyd/spotifyd.conf:/etc/spotifyd.conf"
			- "/etc/asound.conf:/etc/asound.conf"
		group_add:
			- "${AUDIO_GRP}"
