name: build

on:
  push:
    tags:
      - 'v*'
    paths-ignore:
    - 'README.md'

jobs:
  buildx:
    runs-on: ubuntu-20.04
    strategy:
      matrix: 
        profile: [alsa, alsa-dbus, pulseaudio, pulseaudio-dbus]
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      - 
        name: Get Version
        id: get_version
        uses: battila7/get-version-action@v2.2.1
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Available platforms
        run: echo ${{ steps.buildx.outputs.platforms }}
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUBUNAME }}
          password: ${{ secrets.DOCKERHUBTOKEN }} 
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile.${{ matrix.profile }}
          builder: ${{ steps.buildx.outputs.name }}
          platforms: linux/arm/v7,linux/arm64,linux/386,linux/amd64
          push: true
          tags: |
            hvalev/spotifyd-${{ matrix.profile }}:${{ steps.get_version.outputs.version-without-v }}
            hvalev/spotifyd-${{ matrix.profile }}:latest
      - 
        name: Docker Hub Description
        uses: peter-evans/dockerhub-description@v2
        env:
           DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUBUNAME }}
           DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUBPWD }}
           DOCKERHUB_REPOSITORY: spotifyd-${{ matrix.profile }}